title: Diarina
description: 技术博客与个人空间
baseurl: ""
url: "https://diarina.com"

# 文章链接格式
permalink: /posts/:year/:month/:day/:title/

# 启用的插件
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 默认布局设置
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"